devices: [0]
pretrained_model_path: null
train_data_path: /home/inzapp/train_data/mnist/train
validation_data_path: /home/inzapp/train_data/mnist/validation
input_rows: 32
input_cols: 32
input_channels: 3
model_name: test_boilerplate
optimizer: sgd
lr_policy: step
lr: 0.001
lrf: 0.05
l2: 0.0005
warm_up: 1000
momentum: 0.9
batch_size: 32
max_q_size: 1024
iterations: 10000
checkpoint_interval: 2000
show_progress: true
fix_seed: false
